#!/bin/bash

# Autostart
~/.local/bin/eww daemon
riverctl spawn "waybar"
riverctl spawn "~/.local/bin/kile"
riverctl spawn "pipewire"
riverctl spawn "pipewire-pulse"
riverctl spawn "pipewire-media-session"
riverctl spawn "mpd"
riverctl spawn "mpDris2"
riverctl spawn "/usr/lib/kdeconnectd"
riverctl spawn "lxpolkit"
riverctl spawn "dunst"
riverctl spawn "exec wl-paste -t text --watch clipman store --no-persist"
riverctl spawn '~/.config/river/scripts/idle\
  -c 700 "wlopm --off *" -r "wlopm --on *"\
  -c 900 "swaylock -f"'


# Sourcing layouts
source ~/.config/river/layout

# Wallpaper
riverctl spawn "swaybg -o '*' '-c' '#111111'"

# Use the "logo" key as the primary modifier
mod="Mod4"

# Mod+Shift+Return to start an instance of Alacritty
riverctl map normal $mod Return spawn alacritty

# Launch wofi -run
riverctl map normal $mod R spawn "dmenu_path | wofi --dmenu -p run | sh"

# Open up clipman history manager and clear it
riverctl map normal Mod1 Space spawn "clipman pick -t wofi -T'--dmenu -p clipboard'"
riverctl map normal Mod1+Shift Space spawn "clipman clear --all"

# Mod + Tab changes to last tag
riverctl map normal $mod Tab focus-previous-tags

# Launch wofi -drun
riverctl map normal $mod D spawn "wofi --show drun -p start"

# Screen lock
riverctl map normal $mod f1 spawn swaylock

# Cursor behaviour
riverctl focus-follows-cursor normal

# Mod+Q to close the focused view
riverctl map normal $mod Q close

# Mod+P to open the power menu
riverctl map normal $mod P spawn "~/.local/bin/eww open --toggle power"

# Mod+Shift+P to exit river
riverctl map normal $mod+Shift P exit

# Mod+T for the layout switcher
riverctl map normal $mod T spawn ~/.config/river/scripts/switcher

# Mod+K and Mod+J to focus the next/previous view in the layout stack
riverctl map normal $mod K focus-view next
riverctl map normal $mod J focus-view previous

# Mod+Shift+K and Mod+Shift+J to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift K swap next
riverctl map normal $mod+Shift J swap previous

# Screenshot with Swappy
riverctl map normal Mod1 print spawn "grimshot --notify copy area"
riverctl map normal None print spawn "grimshot --notify copy output"

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period spawn "riverctl send-to-output next"
riverctl map normal $mod+Shift Comma spawn "riverctl send-to-output previous"
riverctl set-cursor-warp on-output-change

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+Return to bump the focused view to the top of the layout stack, making
# it the new master
riverctl map normal $mod+Shift Return zoom

# Keybindings for kile
layout="kile"

# Mod+H and Mod+L to decrease/increase the width of the master column by 5%
riverctl map normal $mod H send-layout-cmd "${layout}" "mod_main_ratio -0.05"
riverctl map normal $mod L send-layout-cmd "${layout}" "mod_main_ratio 0.05"

# Mod+Shift+{K, L} to increment/decrement the number of master views in the layout
riverctl map normal $mod+Control L send-layout-cmd "${layout}" "mod_main_amount 1"

riverctl map normal $mod+Control H send-layout-cmd  "${layout}" "mod_main_amount -1"

# Declaring tags and their keybinds
for key in 1 2 3 4 5 6 7 8 9
do
  case "$key" in
    1|2|3|4|5|6|7|8|9)
      i=$key
      ;;
  esac
  tagmask=$((1 << ($i - 1)))

  # Mod+{M, N, B} to focus tag [20-22]
  riverctl map normal $mod $key set-focused-tags $tagmask

  # Mod+Shift+{M, N, B} to tag focused view with tag [20-22]
  riverctl map normal $mod+Shift $key set-view-tags $tagmask

  # Mod+Ctrl+{M, N, B} to toggle focus of tag [20-22]
  riverctl map normal $mod+Control $key toggle-focused-tags $tagmask

  # Mod+Shift+Ctrl+{M, N, B} to toggle tag [20-22] of focused view
  riverctl map normal $mod+Mod1 $key toggle-view-tags $tagmask
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags_mask=255
riverctl map normal $mod '0' set-focused-tags $all_tags_mask
riverctl map normal $mod+Shift '0' set-view-tags $all_tags_mask

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Toggle and reload waybar
riverctl map normal $mod B spawn "killall -SIGUSR1 waybar"
riverctl map normal $mod+Shift B spawn "killall -SIGUSR2 waybar"

# Reload kile config
riverctl map normal $mod+Shift I spawn "~/.config/river/configure-kile; notify-send 'Kile reconfigured'"

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# Mod+Space to toggle float
riverctl map normal $mod Space toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping
riverctl map normal None XF86Eject             spawn eject -T
riverctl map normal None XF86AudioRaiseVolume  spawn ~/.scripts/system/volume up
riverctl map normal None XF86AudioLowerVolume  spawn ~/.scripts/system/volume down
riverctl map normal None XF86AudioMute         spawn pamixer --toggle-mute
riverctl map normal None XF86AudioMedia        spawn playerctl play-pause
riverctl map normal None XF86AudioPlay         spawn playerctl play-pause
riverctl map normal None XF86AudioPrev         spawn playerctl previous
riverctl map normal None XF86AudioNext         spawn playerctl next
riverctl map normal None XF86MonBrightnessUp   spawn light -A 5
riverctl map normal None XF86MonBrightnessDown spawn light -U 5

# Set repeat rate
riverctl set-repeat 50 300

# Set app-ids of views which should float
riverctl float-filter-add "float"
riverctl float-filter-add "popup"
riverctl float-filter-add "swappy"
riverctl float-filter-add "imv"

# Set app-ids of views which should use client side decorations
riverctl csd-filter-add "swappy"

# Set opacity and fade effect (removed, possibly revived in the future)
# riverctl opacity 1.0 1.0 0.0 0.1 30

# Border color focused
riverctl border-color-focused "0x61AFEF"

# Border color focused
riverctl border-color-unfocused "0x333333"

# Border width
riverctl border-width 4

# Attach-mode
riverctl attach-mode bottom

# Default layout
riverctl default-layout kile

# Kile configuration
source ~/.config/river/configure-kile

# Stuff that should start last because waybar is slow sometimes

sleep 1

riverctl spawn "nm-applet --indicator"
riverctl spawn "blueman-applet"
