#!/bin/bash

source ~/.config/river/layout

riverctl send-layout-cmd kile "outer_padding 6"
riverctl send-layout-cmd kile "view_padding 6"
riverctl focus-output next
riverctl send-layout-cmd kile "order ascend"
riverctl send-layout-cmd kile "all ${STACKTILE}"
