#!/bin/bash

# Nested layouts (examples)

# This layout doesn't have a name because it's used in others
ROW="((h: h d) 2 0.65)"

HORIZONTAL="
((h:
    v
    ((v: f d) 1 0.5)) 1 0.62)"

# An example for conditional layouts
MOSAIC="mosaic
((3 > ( v:
	$HORIZONTAL
    ((h: f d) 1 0.62)
  ) ? ((v: h h) 1)) 3 0.6)"

STACK="stack
((v:
    $ROW
    $ROW) 1 0.57)"

CENTERED="centered
((v:
  	$ROW
    ((h: f d) 1 0.63)
  	$ROW
  ) 1 0.47 1)"

# Inspired by Stacktile - https://git.sr.ht/~leon_plickat/stacktile
# Fixed to be reversed like all other layouts
STACKTILE="stacktile
((v: h
	((h: f d) 1 0.55))
    1 0.6 0)"


