#!/bin/sh

tabletvalues="$(xinput | awk '/UGTABLET/' | grep -o "id=[[:digit:]][[:digit:]]" | grep -o "[[:digit:]][[:digit:]]")"

echo $tabletvalues


for fn in $tabletvalues; do
    xinput map-to-output $fn HDMI-1
done
