#!/bin/bash

# Simple script to handle a DIY shutdown menu. When run you should see a bunch of options (shutdown, reboot etc.)
#
# Requirements:
# - rofi
# - systemd, but you can replace the commands for OpenRC or anything else
#
# Instructions:
# - Save this file as power.sh or anything
# - Give it exec priviledge, or chmod +x /path/to/power.sh
# - Run it

chosen=$(echo -e "[Cancel]\nTablet Mirror\nTablet Extend\nDisplay Port 1\nDisplay Port 2\nDisplay Port 3" | dmenu -l 8 -fn "JetBrainsMono NF")
# Info about some states are available here:
# https://www.freedesktop.org/software/systemd/man/systemd-sleep.conf.html#Description

if [[ $chosen = "Tablet Mirror" ]]; then
	xrandr --output HDMI-1 --mode 1920x1080 --same-as DP-1 --scale 1.5x1.5
elif [[ $chosen = "Tablet Extend" ]]; then
	xrandr --output HDMI-1 --mode 1920x1080 --pos 0x1440 --scale 1x1
elif [[ $chosen = "Display Port 1" ]]; then
xrandr --output DP-1
elif [[ $chosen = "Display Port 2" ]]; then
xrandr --output DP-2
elif [[ $chosen = "Display Port 3" ]]; then
xrandr --output DP-3
fi
