#! /bin/bash
# Give dmenu a list of spanish characters to copy
# Notifies which character has been copied

grep -v "#" ~/.scripts/special-characters/accents | dmenu -l 20 | awk '{print $1}' | tr -d '\n' | xclip -selection c

if ! ([ "$(xclip -o -selection c)" = '' ] || [ "$(xclip -o -selection c)" = '[X]' ]) then
  pgrep -x dunst >/dev/null && notify-send "$(xclip -o -selection c) copied to clipboard"
  exit 2
fi
