#! /bin/sh

## Killall

killall volumeicon
killall greenclip
killall dunst
killall mpDris2
killall mpd
killall lxsession
killall nm-applet
killall blueman-applet
killall picom
killall kdeconnectd

## Startup

# Volume

volumeicon &

# keybinds

~/.scripts/system/sxhkd-start &

# Greenclip

greenclip daemon &

# setupkeyboard
~/.scripts/system/keyboardsetup &

# Notifications

exec dunst &

# mpd

mpDris2 &

# Walpaper

exec nitrogen --restore &

# Lxsession

exec lxsession &

# Picom

picom --experimental-backends -b &

# Wifi stuff and Bluetooth, not needed for a desktop but why not

nm-applet 2>&1 > /dev/null
blueman-applet &

# Kde connect

/usr/lib/kdeconnectd &
