#! /bin/sh

## Killall

killall volumeicon
killall greenclip
killall dunst
killall mpDris2
killall mpd
killall lxsession
killall wpa-cute
killall blueman-applet
killall picom
killall kdeconnectd

sleep 1

## Startup

# Volume

volumeicon &

# keybinds

~/.scripts/system/sxhkd-start &

# Greenclip

greenclip daemon &

# setupkeyboard
~/.scripts/system/keyboardsetup &

# Notifications

exec dunst &

# mpd

mpDris2 &

# Walpaper

exec nitrogen --restore &

# Lxsession

lxsession &

# Picom

exec picom --experimental-backends -b &

# Wifi stuff and Bluetooth
wpa-cute -t &

blueman-applet &

# Audio
pulseaudio &

# Kde connect

/usr/lib/kdeconnectd &
