#! /bin/sh

curl -s https://corona-stats.online/states/US > ~/.cache/corona

grep "Puerto Rico" ~/.cache/corona |
  sed "s/\s*//g ; s/║//g ; s/│/;/g ; s/\x1b\[[0-9;]*m//g" |
  awk -F';' '{print " ﯭ"  " "$3"" " ("$4")" " " " "$5"" " ("$6")"}'
