#!/bin/bash

# Sourcing layouts for river
source ~/.config/river/layout

# The namespace of the layout client
NAMESPACE=kile

# Launch menu prompt
LAYOUT=$(wofi --dmenu 2> /dev/null << EOM
centered
stack
mosaic
stacktile
EOM
)

# Selecting the appropriate layout
case $LAYOUT in
  centered)
    LAYOUT=$CENTERED
    ;;
  stack)
    LAYOUT=$STACK
    ;;
  stacktile)
    LAYOUT=$STACKTILE
    ;;
  mosaic)
    LAYOUT=$MOSAIC
    ;;
  *)
    LAYOUT=""
    ;;
esac

if [[ $LAYOUT != "" ]]; then
  riverctl send-layout-cmd "$NAMESPACE" "focused $LAYOUT"
fi
